name: thimar_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  kiwi: ^5.0.0
  image_picker: ^1.0.7
  easy_localization: ^3.0.4
  flutter_svg: ^0.23.0+1
  flutter_screenutil: ^5.9.0
  flutter_html: ^3.0.0-alpha.5
  intl: ^0.18.1
  animate_do: ^3.3.3
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  shared_preferences: ^2.2.2
  circular_countdown_timer: ^0.2.3
  dotted_border: ^2.0.0+1
  google_maps_flutter: ^2.5.3
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - assets/svg/

  